[program:agnishop-scheduler]
process_name=%(program_name)s
directory=/opt/agnishopbjm/backend
command=php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/opt/agnishopbjm/backend/storage/logs/agnishop-scheduler.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=60
