[program:agnishop-worker]
process_name=%(program_name)s
directory=/opt/agnishopbjm/backend
command=php artisan queue:work --sleep=3 --tries=3 --timeout=120 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/opt/agnishopbjm/backend/storage/logs/agnishop-worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=180
